//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_Library.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess_Library.Resources.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to keep show this dialog?.
        /// </summary>
        internal static string checkbox_continue_message {
            get {
                return ResourceManager.GetString("checkbox_continue_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Form_Message {
            get {
                return ResourceManager.GetString("Form_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string Form_Promotion {
            get {
                return ResourceManager.GetString("Form_Promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose what chessman you want to promote : .
        /// </summary>
        internal static string labelX_form_promotion {
            get {
                return ResourceManager.GetString("labelX_form_promotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat this position 3 times .
        /// </summary>
        internal static string Result_3timesrepeat {
            get {
                return ResourceManager.GetString("Result_3timesrepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black side has no more move.
        /// </summary>
        internal static string Result_BlackNoMoreMove {
            get {
                return ResourceManager.GetString("Result_BlackNoMoreMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black side ran out of time .
        /// </summary>
        internal static string Result_BlackOutOfTime {
            get {
                return ResourceManager.GetString("Result_BlackOutOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black wins.
        /// </summary>
        internal static string Result_BlackWin {
            get {
                return ResourceManager.GetString("Result_BlackWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        internal static string Result_Check {
            get {
                return ResourceManager.GetString("Result_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmate.
        /// </summary>
        internal static string Result_Checkmate {
            get {
                return ResourceManager.GetString("Result_Checkmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer has no more move.
        /// </summary>
        internal static string Result_ComputerNoMoreMove {
            get {
                return ResourceManager.GetString("Result_ComputerNoMoreMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer ran out of time .
        /// </summary>
        internal static string Result_ComputerOutOfTime {
            get {
                return ResourceManager.GetString("Result_ComputerOutOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer wins.
        /// </summary>
        internal static string Result_ComputerWin {
            get {
                return ResourceManager.GetString("Result_ComputerWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw.
        /// </summary>
        internal static string Result_Draw {
            get {
                return ResourceManager.GetString("Result_Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similarity of force, can&apos;t checkmate.
        /// </summary>
        internal static string Result_DrawCantCheckmate {
            get {
                return ResourceManager.GetString("Result_DrawCantCheckmate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human has no more move.
        /// </summary>
        internal static string Result_HumanNoMoreMove {
            get {
                return ResourceManager.GetString("Result_HumanNoMoreMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human ran out of time .
        /// </summary>
        internal static string Result_HumanOutOfTime {
            get {
                return ResourceManager.GetString("Result_HumanOutOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human wins.
        /// </summary>
        internal static string Result_HumanWin {
            get {
                return ResourceManager.GetString("Result_HumanWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White side has no more move.
        /// </summary>
        internal static string Result_WhiteNoMoreMove {
            get {
                return ResourceManager.GetString("Result_WhiteNoMoreMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White side ran out of time.
        /// </summary>
        internal static string Result_WhiteOutOfTime {
            get {
                return ResourceManager.GetString("Result_WhiteOutOfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White wins.
        /// </summary>
        internal static string Result_WhiteWin {
            get {
                return ResourceManager.GetString("Result_WhiteWin", resourceCulture);
            }
        }
    }
}
