//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess_game.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess_game.Resources.Lang.langres", typeof(langres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess.
        /// </summary>
        internal static string About_Box {
            get {
                return ResourceManager.GetString("About_Box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author .
        /// </summary>
        internal static string btn_Author {
            get {
                return ResourceManager.GetString("btn_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btn_Cancel {
            get {
                return ResourceManager.GetString("btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture screen.
        /// </summary>
        internal static string btn_Capture {
            get {
                return ResourceManager.GetString("btn_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess rule .
        /// </summary>
        internal static string btn_Chessrule {
            get {
                return ResourceManager.GetString("btn_Chessrule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string btn_Exit {
            get {
                return ResourceManager.GetString("btn_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string btn_Hint {
            get {
                return ResourceManager.GetString("btn_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string btn_Language {
            get {
                return ResourceManager.GetString("btn_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load game.
        /// </summary>
        internal static string btn_Loadgame {
            get {
                return ResourceManager.GetString("btn_Loadgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New game.
        /// </summary>
        internal static string btn_Newgame {
            get {
                return ResourceManager.GetString("btn_Newgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string btn_Options {
            get {
                return ResourceManager.GetString("btn_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string btn_Redo {
            get {
                return ResourceManager.GetString("btn_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save .
        /// </summary>
        internal static string btn_Save {
            get {
                return ResourceManager.GetString("btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save game.
        /// </summary>
        internal static string btn_Savegame {
            get {
                return ResourceManager.GetString("btn_Savegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save moved .
        /// </summary>
        internal static string btn_Savemoved {
            get {
                return ResourceManager.GetString("btn_Savemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start .
        /// </summary>
        internal static string btn_Start {
            get {
                return ResourceManager.GetString("btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string btn_Undo {
            get {
                return ResourceManager.GetString("btn_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string buttonItem1 {
            get {
                return ResourceManager.GetString("buttonItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound .
        /// </summary>
        internal static string ckb_Sound {
            get {
                return ResourceManager.GetString("ckb_Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player vs Computer.
        /// </summary>
        internal static string combobox_Game_Mode {
            get {
                return ResourceManager.GetString("combobox_Game_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player vs Computer.
        /// </summary>
        internal static string combobox_GameMode_itemvsCom {
            get {
                return ResourceManager.GetString("combobox_GameMode_itemvsCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player vs Player.
        /// </summary>
        internal static string combobox_GameMode_itemvsPlayer {
            get {
                return ResourceManager.GetString("combobox_GameMode_itemvsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        internal static string Form_Change_Language {
            get {
                return ResourceManager.GetString("Form_Change_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess - Nguyen Trong Hoang Viet.
        /// </summary>
        internal static string Form_Main {
            get {
                return ResourceManager.GetString("Form_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string Form_New_game {
            get {
                return ResourceManager.GetString("Form_New_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Form_Options {
            get {
                return ResourceManager.GetString("Form_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string grp_Style {
            get {
                return ResourceManager.GetString("grp_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha Noi University of Science and Technology .
        /// </summary>
        internal static string labelCompanyName {
            get {
                return ResourceManager.GetString("labelCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Nguyen Trong Hoang Viet .
        /// </summary>
        internal static string labelCopyright {
            get {
                return ResourceManager.GetString("labelCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chess .
        /// </summary>
        internal static string labelProductName {
            get {
                return ResourceManager.GetString("labelProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.
        /// </summary>
        internal static string labelVersion {
            get {
                return ResourceManager.GetString("labelVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of ChessBoard.
        /// </summary>
        internal static string lbl_BoardStyle {
            get {
                return ResourceManager.GetString("lbl_BoardStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of Cell : .
        /// </summary>
        internal static string lbl_CellSize {
            get {
                return ResourceManager.GetString("lbl_CellSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of Chessman :  .
        /// </summary>
        internal static string lbl_ChessPieceSize {
            get {
                return ResourceManager.GetString("lbl_ChessPieceSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style of ChessMan.
        /// </summary>
        internal static string lbl_ChessPieceStyle {
            get {
                return ResourceManager.GetString("lbl_ChessPieceStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Side : .
        /// </summary>
        internal static string lbl_ChooseSide {
            get {
                return ResourceManager.GetString("lbl_ChooseSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Time : .
        /// </summary>
        internal static string lbl_ExtraTime {
            get {
                return ResourceManager.GetString("lbl_ExtraTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Options .
        /// </summary>
        internal static string lbl_Form_Newgame {
            get {
                return ResourceManager.GetString("lbl_Form_Newgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string lbl_Form_Option {
            get {
                return ResourceManager.GetString("lbl_Form_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Mode :.
        /// </summary>
        internal static string lbl_GameMode {
            get {
                return ResourceManager.GetString("lbl_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level :.
        /// </summary>
        internal static string lbl_Level {
            get {
                return ResourceManager.GetString("lbl_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes .
        /// </summary>
        internal static string lbl_Minute {
            get {
                return ResourceManager.GetString("lbl_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        internal static string lbl_Second {
            get {
                return ResourceManager.GetString("lbl_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Max : .
        /// </summary>
        internal static string lbl_TimeMax {
            get {
                return ResourceManager.GetString("lbl_TimeMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string radiobtn_Black {
            get {
                return ResourceManager.GetString("radiobtn_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        internal static string radiobtn_Easy {
            get {
                return ResourceManager.GetString("radiobtn_Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard .
        /// </summary>
        internal static string radiobtn_Hard {
            get {
                return ResourceManager.GetString("radiobtn_Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string radiobtn_Medium {
            get {
                return ResourceManager.GetString("radiobtn_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White ( Play first ).
        /// </summary>
        internal static string radiobtn_White {
            get {
                return ResourceManager.GetString("radiobtn_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string ribbonTabItem_Auxiliaryfunction {
            get {
                return ResourceManager.GetString("ribbonTabItem_Auxiliaryfunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string ribbonTabItem_Help {
            get {
                return ResourceManager.GetString("ribbonTabItem_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string ribbonTabItem_Home {
            get {
                return ResourceManager.GetString("ribbonTabItem_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact of Author : 
        ///
        ///Email : vieritolove@gmail.com
        ///Facebook : facebook.com/vieritolove.
        /// </summary>
        internal static string textBoxDescription {
            get {
                return ResourceManager.GetString("textBoxDescription", resourceCulture);
            }
        }
    }
}
